---
- hosts: homarr
  become: true

  vars_files:
    - vars.yml
    - - ../../vault.yml

  pre_tasks:
    - name: update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

  roles:
    - firewall
    - geerlingguy.nodejs
    - homarr