---
- hosts: all
  remote_user: root
  become: true

  # vars:
  #   ansible_user: root
  #   ansible_private_key_file: "../.ssh/homelab"

  vars_files:
    - vars.yml
    - ../../vault.yml

  pre_tasks:
    - name: update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

  roles:
    - security