---
- hosts: all
  become: true

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

  roles:
    - security
    - firewall
    - ansible-role-nodejs
    - uptime-kuma